//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Electricity_Bill__Calculator.EBC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Pemakaian_PerMenitOperationCompleted;
        
        private System.Threading.SendOrPostCallback Pemakaian_PerJamOperationCompleted;
        
        private System.Threading.SendOrPostCallback Pemakaian_PerHariOperationCompleted;
        
        private System.Threading.SendOrPostCallback Pemakaian_PerBulanOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Electricity_Bill__Calculator.Properties.Settings.Default.Electricity_Bill__Calculator_EBC_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Pemakaian_PerMenitCompletedEventHandler Pemakaian_PerMenitCompleted;
        
        /// <remarks/>
        public event Pemakaian_PerJamCompletedEventHandler Pemakaian_PerJamCompleted;
        
        /// <remarks/>
        public event Pemakaian_PerHariCompletedEventHandler Pemakaian_PerHariCompleted;
        
        /// <remarks/>
        public event Pemakaian_PerBulanCompletedEventHandler Pemakaian_PerBulanCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pemakaian_PerMenit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Pemakaian_PerMenit(double watt, int jumlah_menit, double tarif_perkwh) {
            object[] results = this.Invoke("Pemakaian_PerMenit", new object[] {
                        watt,
                        jumlah_menit,
                        tarif_perkwh});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Pemakaian_PerMenitAsync(double watt, int jumlah_menit, double tarif_perkwh) {
            this.Pemakaian_PerMenitAsync(watt, jumlah_menit, tarif_perkwh, null);
        }
        
        /// <remarks/>
        public void Pemakaian_PerMenitAsync(double watt, int jumlah_menit, double tarif_perkwh, object userState) {
            if ((this.Pemakaian_PerMenitOperationCompleted == null)) {
                this.Pemakaian_PerMenitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPemakaian_PerMenitOperationCompleted);
            }
            this.InvokeAsync("Pemakaian_PerMenit", new object[] {
                        watt,
                        jumlah_menit,
                        tarif_perkwh}, this.Pemakaian_PerMenitOperationCompleted, userState);
        }
        
        private void OnPemakaian_PerMenitOperationCompleted(object arg) {
            if ((this.Pemakaian_PerMenitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Pemakaian_PerMenitCompleted(this, new Pemakaian_PerMenitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pemakaian_PerJam", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Pemakaian_PerJam(double watt, int jumlah_jam, double tarif_perkwh) {
            object[] results = this.Invoke("Pemakaian_PerJam", new object[] {
                        watt,
                        jumlah_jam,
                        tarif_perkwh});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Pemakaian_PerJamAsync(double watt, int jumlah_jam, double tarif_perkwh) {
            this.Pemakaian_PerJamAsync(watt, jumlah_jam, tarif_perkwh, null);
        }
        
        /// <remarks/>
        public void Pemakaian_PerJamAsync(double watt, int jumlah_jam, double tarif_perkwh, object userState) {
            if ((this.Pemakaian_PerJamOperationCompleted == null)) {
                this.Pemakaian_PerJamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPemakaian_PerJamOperationCompleted);
            }
            this.InvokeAsync("Pemakaian_PerJam", new object[] {
                        watt,
                        jumlah_jam,
                        tarif_perkwh}, this.Pemakaian_PerJamOperationCompleted, userState);
        }
        
        private void OnPemakaian_PerJamOperationCompleted(object arg) {
            if ((this.Pemakaian_PerJamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Pemakaian_PerJamCompleted(this, new Pemakaian_PerJamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pemakaian_PerHari", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Pemakaian_PerHari(double watt, int jumlah_jam, int jumlah_menit, double tarif_perkwh) {
            object[] results = this.Invoke("Pemakaian_PerHari", new object[] {
                        watt,
                        jumlah_jam,
                        jumlah_menit,
                        tarif_perkwh});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Pemakaian_PerHariAsync(double watt, int jumlah_jam, int jumlah_menit, double tarif_perkwh) {
            this.Pemakaian_PerHariAsync(watt, jumlah_jam, jumlah_menit, tarif_perkwh, null);
        }
        
        /// <remarks/>
        public void Pemakaian_PerHariAsync(double watt, int jumlah_jam, int jumlah_menit, double tarif_perkwh, object userState) {
            if ((this.Pemakaian_PerHariOperationCompleted == null)) {
                this.Pemakaian_PerHariOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPemakaian_PerHariOperationCompleted);
            }
            this.InvokeAsync("Pemakaian_PerHari", new object[] {
                        watt,
                        jumlah_jam,
                        jumlah_menit,
                        tarif_perkwh}, this.Pemakaian_PerHariOperationCompleted, userState);
        }
        
        private void OnPemakaian_PerHariOperationCompleted(object arg) {
            if ((this.Pemakaian_PerHariCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Pemakaian_PerHariCompleted(this, new Pemakaian_PerHariCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pemakaian_PerBulan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Pemakaian_PerBulan(double watt, int jumlah_jam, double jumlah_menit, double tarif_perkwh, int hari) {
            object[] results = this.Invoke("Pemakaian_PerBulan", new object[] {
                        watt,
                        jumlah_jam,
                        jumlah_menit,
                        tarif_perkwh,
                        hari});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Pemakaian_PerBulanAsync(double watt, int jumlah_jam, double jumlah_menit, double tarif_perkwh, int hari) {
            this.Pemakaian_PerBulanAsync(watt, jumlah_jam, jumlah_menit, tarif_perkwh, hari, null);
        }
        
        /// <remarks/>
        public void Pemakaian_PerBulanAsync(double watt, int jumlah_jam, double jumlah_menit, double tarif_perkwh, int hari, object userState) {
            if ((this.Pemakaian_PerBulanOperationCompleted == null)) {
                this.Pemakaian_PerBulanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPemakaian_PerBulanOperationCompleted);
            }
            this.InvokeAsync("Pemakaian_PerBulan", new object[] {
                        watt,
                        jumlah_jam,
                        jumlah_menit,
                        tarif_perkwh,
                        hari}, this.Pemakaian_PerBulanOperationCompleted, userState);
        }
        
        private void OnPemakaian_PerBulanOperationCompleted(object arg) {
            if ((this.Pemakaian_PerBulanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Pemakaian_PerBulanCompleted(this, new Pemakaian_PerBulanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Pemakaian_PerMenitCompletedEventHandler(object sender, Pemakaian_PerMenitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pemakaian_PerMenitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Pemakaian_PerMenitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Pemakaian_PerJamCompletedEventHandler(object sender, Pemakaian_PerJamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pemakaian_PerJamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Pemakaian_PerJamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Pemakaian_PerHariCompletedEventHandler(object sender, Pemakaian_PerHariCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pemakaian_PerHariCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Pemakaian_PerHariCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Pemakaian_PerBulanCompletedEventHandler(object sender, Pemakaian_PerBulanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pemakaian_PerBulanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Pemakaian_PerBulanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591